// AUTO-GENERATED by scripts/optimize-images.js — do not edit by hand.
// Maps a decoded /public image path to its pre-generated WebP variants.

export type OptimizedVariant = { slug: string; widths: number[] };

export const OPTIMIZED_IMAGES: Record<string, OptimizedVariant> = {
  "/hero-bg.png": {
    "slug": "hero-bg",
    "widths": [
      480,
      768,
      1280,
      1920
    ]
  },
  "/metabol hero image.png": {
    "slug": "metabol-hero-image",
    "widths": [
      480,
      547
    ]
  },
  "/left leaf element.png": {
    "slug": "left-leaf-element",
    "widths": [
      480,
      768,
      814
    ]
  },
  "/right leaf element.png": {
    "slug": "right-leaf-element",
    "widths": [
      480,
      705
    ]
  },
  "/stone base.png": {
    "slug": "stone-base",
    "widths": [
      480,
      768,
      1254
    ]
  },
  "/science heo bg.png": {
    "slug": "science-heo-bg",
    "widths": [
      480,
      768,
      1280,
      1672
    ]
  },
  "/science hero image.png": {
    "slug": "science-hero-image",
    "widths": [
      480,
      768,
      1254
    ]
  },
  "/our story hero.png": {
    "slug": "our-story-hero",
    "widths": [
      480,
      768,
      1254
    ]
  },
  "/immunity-power-pack-hero.png": {
    "slug": "immunity-power-pack-hero",
    "widths": [
      480,
      768,
      1280,
      1448
    ]
  },
  "/nutrizen-logo.png": {
    "slug": "nutrizen-logo",
    "widths": [
      480,
      768,
      850
    ]
  }
};
