/**
 * Pre-generate responsive WebP variants for heavy LOCAL images.
 *
 * Why: next.config images.loader is "custom" (shopify-image-loader) so the
 * built-in /_next/image optimizer never runs. For Shopify URLs that's fine
 * (Shopify CDN resizes). For local /public images it meant the raw full-size
 * PNG was shipped to every device. This script bakes resized WebP variants
 * that the loader maps to via src/lib/optimized-images.ts.
 *
 * Run:  npm i -D sharp  (one-time; not a runtime dep)
 *       node scripts/optimize-images.js
 * Output: public/optimized/<slug>/<width>.webp  +  src/lib/optimized-images.ts
 *
 * Re-run whenever a source image in SOURCES changes, then commit the generated
 * public/optimized/** and src/lib/optimized-images.ts. Production serves those
 * committed files directly, so sharp is never needed at build/runtime.
 */
const sharp = require("sharp");
const fs = require("fs");
const path = require("path");

const PUBLIC_DIR = path.join(__dirname, "../public");
const OUT_DIR = path.join(PUBLIC_DIR, "optimized");
const MANIFEST = path.join(__dirname, "../src/lib/optimized-images.ts");

// Responsive width buckets. Capped per-image to the source's native width
// (never upscale). Mobile gets 480/768; desktop 1280/1920.
const WIDTH_BUCKETS = [480, 768, 1280, 1920];
const QUALITY = 80;

// Heavy local images served through next/image in production.
// (Mock-only product thumbnails are skipped — live store uses Shopify CDN.)
const SOURCES = [
  "hero-bg.png",
  "metabol hero image.png",
  "left leaf element.png",
  "right leaf element.png",
  "stone base.png",
  "science heo bg.png",
  "science hero image.png",
  "our story hero.png",
  "immunity-power-pack-hero.png",
  "nutrizen-logo.png",
];

const slugify = (name) =>
  path.parse(name).name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

async function run() {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const manifest = {};
  let originalTotal = 0;
  let optimizedTotal = 0;

  for (const filename of SOURCES) {
    const inputPath = path.join(PUBLIC_DIR, filename);
    if (!fs.existsSync(inputPath)) {
      console.log(`⚠️  skip ${filename} (not found)`);
      continue;
    }
    const slug = slugify(filename);
    const destDir = path.join(OUT_DIR, slug);
    fs.mkdirSync(destDir, { recursive: true });

    const meta = await sharp(inputPath).metadata();
    const origW = meta.width || Math.max(...WIDTH_BUCKETS);
    const origSize = fs.statSync(inputPath).size;
    originalTotal += origSize;

    // widths < native, plus native itself (so full-res is available), deduped.
    const widths = Array.from(
      new Set([...WIDTH_BUCKETS.filter((w) => w < origW), Math.min(origW, 1920)])
    ).sort((a, b) => a - b);

    const sizes = [];
    for (const w of widths) {
      const outPath = path.join(destDir, `${w}.webp`);
      await sharp(inputPath)
        .resize({ width: w, withoutEnlargement: true })
        .webp({ quality: QUALITY, effort: 5 })
        .toFile(outPath);
      const s = fs.statSync(outPath).size;
      optimizedTotal += s;
      sizes.push(`${(s / 1024).toFixed(0)}KB@${w}`);
    }

    manifest["/" + filename] = { slug, widths };
    console.log(`✅ ${filename}  ${(origSize / 1024).toFixed(0)}KB → ${sizes.join(", ")}`);
  }

  // Emit the manifest the loader reads (keyed by decoded /public path).
  const header =
    "// AUTO-GENERATED by scripts/optimize-images.js — do not edit by hand.\n" +
    "// Maps a decoded /public image path to its pre-generated WebP variants.\n\n" +
    "export type OptimizedVariant = { slug: string; widths: number[] };\n\n" +
    "export const OPTIMIZED_IMAGES: Record<string, OptimizedVariant> = ";
  fs.writeFileSync(MANIFEST, header + JSON.stringify(manifest, null, 2) + ";\n");

  console.log(
    `\n📦 ${(originalTotal / 1024 / 1024).toFixed(2)}MB originals → ` +
      `${(optimizedTotal / 1024 / 1024).toFixed(2)}MB across all variants`
  );
  console.log(`📝 wrote ${path.relative(process.cwd(), MANIFEST)}`);
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
